"""
Layer 5 — LLM Explainer Engine (Step 5 in pipeline)

Takes the scored HedgeOutput from Layer 4 and enriches it with
natural-language explanations generated by an LLM.

Flow per holding:
  1. Build candidates context (PromptBuilder)
  2. Call explainer.explain_candidates() → List[CandidateExplanation]
  3. Merge explanations back into InstrumentCandidate objects

Flow at portfolio level:
  4. Build portfolio context (PromptBuilder)
  5. Call explainer.explain_portfolio() → PortfolioExplanation
  6. Write summary / key_risks / regime_commentary into HedgeOutput

Graceful degradation:
  - If LLM call fails: candidates keep their rule-based rationale/pros/cons
  - If provider not configured: silently skips (returns HedgeOutput as-is)

LLM provider is swapped via settings.llm_provider:
  "claude"  → ClaudeExplainer (Anthropic API)
  "ollama"  → OllamaExplainer (local, no API key needed)
"""
import logging
import time
from typing import Dict, List, Optional

from backend.core.explainer import get_explainer, PromptBuilder
from backend.core.explainer.base_explainer import CandidateExplanation
from backend.models.hedge_models import HedgeOutput, InstrumentCandidate
from backend.models.risk_models import RegimeState, PortfolioRiskSummary
from backend.models.portfolio_models import PortfolioInput

logger = logging.getLogger(__name__)


class LLMExplainerEngine:

    def __init__(self, provider: str = None):
        """
        Args:
            provider: "claude" | "ollama" | None (reads from settings)
        """
        self.explainer = get_explainer(provider)
        self.prompt_builder = PromptBuilder()
        logger.info(f"LLMExplainerEngine using provider: {self.explainer.provider_name}")

    def explain(
        self,
        hedge_output: HedgeOutput,
        portfolio: PortfolioInput,
        risk_summary: PortfolioRiskSummary,
        regime: RegimeState,
    ) -> HedgeOutput:
        """
        Enrich HedgeOutput with LLM-generated explanations.

        Returns the same HedgeOutput object with explanation fields populated.
        Never raises — all LLM failures are caught and logged.
        """
        if not self.explainer.is_available():
            logger.info(
                f"{self.explainer.provider_name} not available — "
                f"hedge output returned without LLM explanations"
            )
            return hedge_output

        t0 = time.perf_counter()

        # Build profile lookup once
        profile_map = {p.ticker: p for p in risk_summary.risk_profiles}

        # Step 1–3: explain candidates for each holding
        for rec in hedge_output.recommendations:
            if not rec.candidates:
                continue

            profile = profile_map.get(rec.asset_ticker)
            if profile is None:
                continue

            holding_notional = profile.notional_value
            context = self.prompt_builder.build_candidates_context(
                asset_ticker=rec.asset_ticker,
                holding_notional=holding_notional,
                risk_profile=profile,
                candidates=rec.candidates,
                regime=regime,
            )

            explanations = self.explainer.explain_candidates(context)
            exp_map = _index_explanations(explanations)

            # Merge LLM text back into each candidate
            for candidate in rec.candidates:
                key = (candidate.ticker, candidate.strategy)
                exp = exp_map.get(key)
                if exp:
                    _apply_explanation(candidate, exp)

        # Step 4–6: portfolio-level narrative
        port_context = self.prompt_builder.build_portfolio_context(
            portfolio=portfolio,
            risk_summary=risk_summary,
            hedge_output=hedge_output,
            regime=regime,
        )
        port_exp = self.explainer.explain_portfolio(port_context)

        hedge_output.portfolio_summary   = port_exp.summary
        hedge_output.key_risks           = port_exp.key_risks
        hedge_output.regime_commentary   = port_exp.regime_commentary
        hedge_output.top_recommendation  = port_exp.top_recommendation
        hedge_output.llm_provider        = self.explainer.provider_name

        elapsed = round(time.perf_counter() - t0, 3)
        logger.info(
            f"LLM explanations generated in {elapsed}s "
            f"({len(hedge_output.recommendations)} holdings)"
        )
        return hedge_output


# ── Helpers ───────────────────────────────────────────────────────────────────

def _index_explanations(
    explanations: List[CandidateExplanation],
) -> Dict[tuple, CandidateExplanation]:
    """Build (ticker, strategy) → CandidateExplanation lookup."""
    return {(e.ticker, e.strategy): e for e in explanations}


def _apply_explanation(
    candidate: InstrumentCandidate,
    exp: CandidateExplanation,
) -> None:
    """
    Merge LLM explanation into InstrumentCandidate in-place.
    Only overwrites fields that the LLM actually filled in (non-empty).
    """
    if exp.when_works_best:
        candidate.when_works_best = exp.when_works_best
    if exp.when_fails:
        candidate.when_fails = exp.when_fails
    if exp.rationale:
        candidate.rationale = exp.rationale
    if exp.pros:
        candidate.pros = exp.pros
    if exp.cons:
        candidate.cons = exp.cons
