from pydantic import BaseModel, Field
from typing import Any, Dict, List, Optional
from datetime import date


class InstrumentCandidate(BaseModel):
    # Identity
    instrument_type: str                # "option" | "future" | "forward" | "swap" | "inverse_etf"
    asset_class: str                    # "equity" | "commodity" | "bond" | "fx" | "crypto"
    ticker: str                         # hedge instrument ticker (SPY, QQQ, GLD …)
    strategy: str = ""                  # "Protective Put" | "Bear Put Spread" | "Collar" …

    # Option-specific (None for non-option instruments)
    strike: Optional[float] = None
    expiry_date: Optional[str] = None   # ISO-8601 string (YYYY-MM-DD)
    option_type: Optional[str] = None   # "put" | "call" | None

    # Hedge relationship to the user's position:
    #   "direct_hedge"  — same underlying, MUST be opposite direction (e.g. long MSFT → put MSFT)
    #   "cross_hedge"   — correlated asset / sector ETF (e.g. long MSFT → put QQQ)
    #   "macro_hedge"   — uncorrelated asset used for diversification (e.g. long SPY → long GLD)
    hedge_category: str = "cross_hedge"

    # Multi-leg strategies (spread / collar): short leg details for L6 re-pricing.
    # If set, L6 prices both legs and returns net Greeks / net cost.
    short_strike: Optional[float] = None       # e.g. K_short for bear put spread
    short_option_type: Optional[str] = None    # "put" or "call"

    # Position
    n_contracts: int = 0

    # Cost / protection
    total_cost: float = 0.0             # total premium outlay in dollars
    max_protection: float = 0.0         # max dollar gain from hedge (optional)

    # Greeks (per-contract basis × n_contracts aggregated in engine)
    delta: float = 0.0
    gamma: float = 0.0
    theta: float = 0.0
    vega: float = 0.0
    rho: float = 0.0
    lambda_leverage: float = 0.0        # capital efficiency = Δ × (S / V)

    # Quality metrics
    basis_risk_r2: float = 0.0          # tail correlation / R² of hedge vs asset
    efficiency_ratio: float = 0.0       # |lambda| — leverage per $ of premium

    # Scoring (0–100)
    score: float = 0.0

    # Explanation (filled by LLM layer in Step 5)
    rationale: str = ""
    pros: List[str] = []
    cons: List[str] = []
    when_works_best: str = ""
    when_fails: str = ""

    # Partial hedge tradeoff table (generated by position_sizer)
    partial_hedge_options: List[Dict[str, Any]] = []

    # Liquidity metrics (populated by Gap 3 liquidity filter)
    liquidity_ok: bool = True           # False if OI < threshold or spread too wide
    open_interest: int = 0
    daily_volume: int = 0
    bid_ask_spread_pct: float = 0.0     # (ask-bid)/mid — lower is better

    # Earnings flag (Gap 9 — IV crush risk)
    earnings_warning: bool = False      # True if expiry crosses a known earnings date
    earnings_date: Optional[str] = None # ISO date of the earnings event in the window

    # Asset-class-specific metrics (populated by L6/L7/L8 engines)
    # IR:       dv01, duration, mod_duration, convexity, yield_level
    # FX:       rho_domestic, rho_foreign, r_domestic, r_foreign
    # Credit:   cs01, dv01, hazard_rate, spread_bps, recovery
    # Commodity: roll_yield_daily
    extended_metrics: Dict[str, Any] = {}


class HedgeRecommendation(BaseModel):
    rank: int
    asset_ticker: str                   # holding ticker being hedged
    candidates: List[InstrumentCandidate]


class HedgeOutput(BaseModel):
    portfolio_notional: float
    regime: str
    is_anomaly: bool
    vix_level: float
    recommendations: List[HedgeRecommendation]
    run_time_seconds: float

    # Filled by Layer 5 (LLM Explainer)
    portfolio_summary: str = ""
    key_risks: List[str] = []
    regime_commentary: str = ""
    top_recommendation: str = ""
    llm_provider: str = ""          # which LLM generated the explanations
